---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Add Datastore
    vmware_host_datastore:
      hostname: '192.168.1.89'
      username: 'administrator@vsphere.local'
      password: 'VMware123!'
      datacenter_name: 'HomeLab'
      datastore_name: 'ds-01'
      datastore_type: 'vmfs'
      vmfs_device_name: 'naa.6000c29d646a30e9dca642b3f846b59a'
      vmfs_version: 6
      esxi_hostname: '192.168.1.90'
      state: present
      validate_certs: false
