---
- hosts: 192.168.1.89
  remote_user: root
  tasks:
  - name: Create Cluster
    local_action:
      module: vmware_cluster
      hostname: 192.168.1.89
      username: 'administrator@vsphere.local'
      password: 'VMware123!'
      datacenter_name: 'HomeLab'
      cluster_name: 'CL-HomeLab'
      state: present
      validate_certs: false
