---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_inventory: hosts
  hosts: vraiaas-servers
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  ansible_connection: winrm
  require_windows_support: true
  ansible_host_key_checking: false
  ansible_platform: windows

verifier:
  name: inspec

platforms:
  - name: windows2012r2-base
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
